// Page Header Constants
export const PAGE_CHANGE_SCREENSIZE		= 'PAGE_CHANGE_SCREENSIZE';
export const PAGE_CHANGE_HAPPENED		= 'PAGE_CHANGE_HAPPENED';
export const PAGE_CHANGE_TITLE			= 'PAGE_CHANGE_TITLE';

// Page Container Constants
export const TEMPLATE_INSERT_REQUEST	= 'TEMPLATE_INSERT_REQUEST';
export const TEMPLATE_INSERT_RECEIVED	= 'TEMPLATE_INSERT_RECEIVED';
export const TEMPLATE_INSERT_ERROR		= 'TEMPLATE_INSERT_ERROR';
export const TEMPLATE_HEAD_REQUEST      = 'TEMPLATE_HEAD_REQUEST';
export const TEMPLATE_HEAD_RECEIVED     = 'TEMPLATE_HEAD_RECEIVED';
export const TEMPLATE_HEAD_ERROR        = 'TEMPLATE_HEAD_ERROR';
export const TEMPLATE_ORDER_CHANGE		= 'TEMPLATE_ORDER_CHANGE';
export const TEMPLATE_DELETE			= 'TEMPLATE_DELETE';
export const TEMPLATE_UPDATE			= 'TEMPLATE_UPDATE';
export const TEMPLATE_GET_REQUEST       = 'TEMPLATE_GET_REQUEST';
export const TEMPLATE_GET_RECEIVED      = 'TEMPLATE_GET_RECEIVED';
export const TEMPLATE_GET_ERROR         = 'TEMPLATE_GET_ERROR';
export const TEMPLATE_ON_DRAG			= 'TEMPLATE_ON_DRAG';
export const PAGE_EVENT_ADDED			= 'PAGE_EVENT_ADDED';
export const PAGE_EMPTY			        = 'PAGE_EMPTY';
export const PAGE_SPLICE_BLOCK			= 'PAGE_SPLICE_BLOCK';
export const PAGE_PUBLISH               = 'PAGE_PUBLISH';
export const UPDATE_STYLE_EDITOR		= 'UPDATE_STYLE_EDITOR';
// External
export const TEMPLATE_EXTERNAL_REQUEST	= 'TEMPLATE_EXTERNAL_REQUEST';
export const TEMPLATE_EXTERNAL_RECEIVED	= 'TEMPLATE_EXTERNAL_RECEIVED';
export const TEMPLATE_EXTERNAL_ERROR		= 'TEMPLATE_EXTERNAL_ERROR';
// Globals
export const TEMPLATE_GLOBAL_REQUEST	= 'TEMPLATE_GLOBAL_REQUEST';
export const TEMPLATE_GLOBAL_RECEIVED	= 'TEMPLATE_GLOBAL_RECEIVED';
export const TEMPLATE_GLOBAL_ERROR		= 'TEMPLATE_GLOBAL_ERROR';

// Block Container Constants
export const PAGE_SPLICE_COLUMN			= 'PAGE_SPLICE_COLUMN';

// Left Menu Constants
export const LEFTMENU_TEMPLATE_REQUEST	= 'LEFTMENU_TEMPLATE_REQUEST';
export const LEFTMENU_TEMPLATE_RECEIVE	= 'LEFTMENU_TEMPLATE_RECEIVE';
export const LEFTMENU_TEMPLATE_ERROR	= 'LEFTMENU_TEMPLATE_ERROR';
export const LEFTMENU_PAGES_REQUEST	    = 'LEFTMENU_PAGES_REQUEST';
export const LEFTMENU_PAGES_RECEIVE	    = 'LEFTMENU_PAGES_RECEIVE';
export const LEFTMENU_PAGES_ERROR	    = 'LEFTMENU_PAGES_ERROR';
export const LEFTMENU_TOGGLE_MENU		= 'LEFTMENU_TOGGLE_MENU';

// Image Library
export const LOAD_LIBRARY_IMAGE_REQUEST	= 'LOAD_LIBRARY_IMAGE_REQUEST';
export const LOAD_LIBRARY_IMAGE_RECEIVE	= 'LOAD_LIBRARY_IMAGE_RECEIVE';
export const LOAD_LIBRARY_IMAGE_ERROR	= 'LOAD_LIBRARY_IMAGE_ERROR';

export const UPLOAD_LIBRARY_IMAGE_REQUEST	= 'UPLOAD_LIBRARY_IMAGE_REQUEST';
export const UPLOAD_LIBRARY_IMAGE_RECEIVE	= 'UPLOAD_LIBRARY_IMAGE_RECEIVE';
export const UPLOAD_LIBRARY_IMAGE_ERROR		= 'UPLOAD_LIBRARY_IMAGE_ERROR';

export const REMOVE_LIBRARY_IMAGE_REQUEST	= 'REMOVE_LIBRARY_IMAGE_REQUEST';
export const REMOVE_LIBRARY_IMAGE_RECEIVE	= 'REMOVE_LIBRARY_IMAGE_RECEIVE';
export const REMOVE_LIBRARY_IMAGE_ERROR		= 'REMOVE_LIBRARY_IMAGE_ERROR';

// File OP
export const LOAD_FILE_REQUEST	= 'LOAD_FILE_REQUEST';
export const LOAD_FILE_RECEIVE	= 'LOAD_FILE_RECEIVE';
export const LOAD_FILE_ERROR	= 'LOAD_FILE_ERROR';

export const SAVE_FILE_REQUEST	= 'SAVE_FILE_REQUEST';
export const SAVE_FILE_RECEIVE	= 'SAVE_FILE_RECEIVE';
export const SAVE_FILE_ERROR	= 'SAVE_FILE_ERROR';

export const UPDATE_STYLE       = 'UPDATE_STYLE';
export const TEMPLATE_STORE     = 'TEMPLATE_STORE';